trailingComma: 'es5'
tabWidth: 2
singleQuote: true
arrowParens: 'always'
quoteProps: 'as-needed'
semi: true
endOfLine: 'crlf'
overrides:
  - files: '*.test.js'
    options:
      semi: true
  - files:
      - '*.html'
    options:
      tabWidth: 4
